---
title: "02 - Get"
author: Jeffrey W. Hollister
layout: post_page
---

```{r setup, echo=FALSE, warning=FALSE}
options(repos="http://cran.rstudio.com/")
```

The second lesson is going to start to lay the foundation for working with data in R.  We will cover some of the very basics of R first, then move on to how you get data into R and how you work with some of the basic data structures.  Lastly, we will cover some ways to find relevant data and pull it directly into R.

##Quick Links to Exercises and R code
- [Lesson 2 R Code](http://jwhollister.com/gedr/rmd_posts/2015-01-14-02-Get.R): All the code from this post in an R Script.

##Lesson Goals
- Understand workflow basics
- Learn R concepts such as assignment and operators
- Learn some useful R functions
- Understand the basic data structures and data types
- Be able to read data into R from a variety of sources
- Interact with data being served from web APIs

##More basics
Before we jump into details on data in R we need to introduce a few of the basics about working in the console, working via scripts, and workspaces/projects.  We will also start working with some simple, yet important R functions.

###Workflow
Being thoughtful about workflow from the beginning of a project is something that gets overlooked a lot, but a little up-front effort can provide a big benefit.  For our purposes we are going to make use of RStudio projects and script **EVERYTHING**.  The console has its utility and we will use it plenty, especially when we are first figuring out how to use commands.  But beyond that, we will store all of our work in a script.  The basic workflow I am going to advocate is:

1. Use a single project for this workshop (we created that in Lesson 1: Exercise 1).
2. Start everything in a script and use copy/paste or the RStudio tools to send to the console.
3. Don't save .RData files or workspace history.  The script should recreate whatever you need.



###Working in the Console



##Data types and structures in R

##Reading data into R

##Where to find data